# Generated by Django 2.2.4 on 2019-09-03 05:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_client_clienttour_tourpack'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourpack',
            old_name='from_to',
            new_name='from_where',
        ),
        migrations.AddField(
            model_name='tourpack',
            name='to',
            field=models.CharField(default=django.utils.timezone.now, max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clienttour',
            name='client_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clienttour_client_id', to='news.Client'),
        ),
        migrations.AlterField(
            model_name='clienttour',
            name='tourpack_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clienttour_tourpack_id', to='news.TourPack'),
        ),
        migrations.AlterField(
            model_name='tourpack',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('FULL', 'Full'), ('EXPIRED', 'Expired'), ('NEW', 'New')], default='Active', max_length=9),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('FULL', 'Full'), ('EXPIRED', 'Expired'), ('NEW', 'New')], default='Active', max_length=9)),
                ('payment_status', models.CharField(choices=[('PAID', 'Paid'), ('NOT_PAID', 'Not Paid')], default='Paid', max_length=9)),
                ('payment_methods', models.CharField(choices=[('VISA', 'Pay w/ Visa Card'), ('MS', 'Pay w/ MasterCard'), ('CRYPTO', 'Pay w/ CRYPTO'), ('PAYPAL', 'Pay w/ Paypal'), ('CASH', 'Pay in cash')], default='Pay in cash', max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clienttour_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_clienttour_id', to='news.ClientTour')),
            ],
        ),
        migrations.CreateModel(
            name='ClientTourParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant_client_id', to='news.Client')),
                ('clienttour_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant_clienttour_id', to='news.ClientTour')),
            ],
        ),
    ]
